Update repos.yml
deepin-community/Repository-Manager pull request #63
Opened 2023-07-03 07:35 UTC by Udacv

add FiraCode

2023-07-03 16:29 UTC, Clansty approved these changes

2023-07-04 02:11 UTC, xzl01 commented
不允许有大写包名

2023-07-04 06:23 UTC, myml requested changes

2023-07-04 06:23 UTC, myml commented on repos.yml
> +  - repo: fonts-FiraCode
包名不能大写

2023-07-04 06:28 UTC, Udacv commented on repos.yml
> +  - repo: fonts-FiraCode
已修改

2023-07-05 01:29 UTC, chenchongbiao approved these changes

2023-07-05 01:29 UTC, chenchongbiao commented
/lgtm

2023-07-05 01:29 UTC, merged