feat: add python3-absl
deepin-community/Repository-Manager pull request #878
Opened 2024-10-05 10:25 UTC by bocchi810

2024-10-08 02:47 UTC, UTsweetyfish requested changes
应当是 python-absl

2024-10-08 11:00 UTC, bocchi810 commented
> 应当是 python-absl

改好了

2024-10-09 02:05 UTC, UTsweetyfish approved these changes

2024-10-09 05:25 UTC, Zeno-sole commented
需要rebase

2024-10-09 15:09 UTC, bocchi810 commented
我不知道哪来的冲突，导致我没法rebase，只能同步后提交了（

2024-10-09 15:11 UTC, merged