add librust-which-dev
deepin-community/Repository-Manager pull request #9
Opened 2023-06-29 09:22 UTC by Komorebi-yaodong

2023-06-29 10:43 UTC, chenchongbiao commented
不需要把源码整个贴上来，实在repos.yml贴上需要新建仓库的名字，你可以看下前面提交的人，另外commit信息只要一个，如果做了修改使用git add . 添加修改，git commit --amend合并到前面的。本地测试下，git指令

2023-06-29 10:43 UTC, chenchongbiao requested changes
不需要把源码整个贴上来，在repos.yml贴上需要新建仓库的名字，你可以看下前面提交的人，源码到时候提交到新建的仓库，另外commit信息只要一个，如果做了修改使用git add . 添加修改，git commit --amend合并到前面的。本地测试下，git指令

2023-06-29 17:30 UTC, Rabenda commented
Add files via upload
上传deb的原因是什么

2023-06-30 01:07 UTC, Zeno-sole commented
@Komorebi-yaodong 注意你创建的仓库名称要用源码名称创建

2023-06-30 01:43 UTC, closed without merging